server:
  port: 8090
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: house
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/houses?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  freemarker:
    charset: UTF-8
    content-type: text/html;charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
    allow-session-override: true
  mail:
    host: smtp.163.com
    username: 13691824094@163.com
    password: sl6819961
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fans.model
logging:
  config: classpath:logback.xml
  level:
    com.fans.mapper: debug
